# Site settings
title: A Good Day 4
header-img: img/HeadImage.jpg
# email: your-email@yourdomain.com
copyright_name: Goodday4
description: "Defining software that helps people have a better weather day"
#url: "http://richcarne.github.io/GoodDay4/"
# twitter_username: SBootstrap
github_username:  RichCarne
# facebook_username:  StartBootstrap
# email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

collections:
  design_docs:
    output: true
    name: "Design Documents"
